class Card:
    def __init__(self, name, value):
        self.name = name
        self.value = value

deck_of_cards = []

deck_of_cards.append(Card("2 of Spades", 2))
deck_of_cards.append(Card("3 of Spades", 3))
deck_of_cards.append(Card("4 of Spades", 4))
deck_of_cards.append(Card("5 of Spades", 5))
deck_of_cards.append(Card("6 of Spades", 6))
deck_of_cards.append(Card("7 of Spades", 7))
deck_of_cards.append(Card("8 of Spades", 8))
deck_of_cards.append(Card("9 of Spades", 9))
deck_of_cards.append(Card("10 of Spades", 10))
deck_of_cards.append(Card("Jack of Spades", 11))
deck_of_cards.append(Card("Queen of Spades", 12))
deck_of_cards.append(Card("King of Spades", 13))
deck_of_cards.append(Card("Ace of Spades", 14))
deck_of_cards.append(Card("2 of Clubs", 2))
deck_of_cards.append(Card("3 of Clubs", 3))
deck_of_cards.append(Card("4 of Clubs", 4))
deck_of_cards.append(Card("5 of Clubs", 5))
deck_of_cards.append(Card("6 of Clubs", 6))
deck_of_cards.append(Card("7 of Clubs", 7))
deck_of_cards.append(Card("8 of Clubs", 8))
deck_of_cards.append(Card("9 of Clubs", 9))
deck_of_cards.append(Card("10 of Clubs", 10))
deck_of_cards.append(Card("Jack of Clubs", 11))
deck_of_cards.append(Card("Queen of Clubs", 12))
deck_of_cards.append(Card("King of Clubs", 13))
deck_of_cards.append(Card("Ace of Clubs", 14))
deck_of_cards.append(Card("2 of Hearts", 2))
deck_of_cards.append(Card("3 of Hearts", 3))
deck_of_cards.append(Card("4 of Hearts", 4))
deck_of_cards.append(Card("5 of Hearts", 5))
deck_of_cards.append(Card("6 of Hearts", 6))
deck_of_cards.append(Card("7 of Hearts", 7))
deck_of_cards.append(Card("8 of Hearts", 8))
deck_of_cards.append(Card("9 of Hearts", 9))
deck_of_cards.append(Card("10 of Hearts", 10))
deck_of_cards.append(Card("Jack of Hearts", 11))
deck_of_cards.append(Card("Queen of Hearts", 12))
deck_of_cards.append(Card("King of Hearts", 13))
deck_of_cards.append(Card("Ace of Hearts", 14))
deck_of_cards.append(Card("2 of Diamonds", 2))
deck_of_cards.append(Card("3 of Diamonds", 3))
deck_of_cards.append(Card("4 of Diamonds", 4))
deck_of_cards.append(Card("5 of Diamonds", 5))
deck_of_cards.append(Card("6 of Diamonds", 6))
deck_of_cards.append(Card("7 of Diamonds", 7))
deck_of_cards.append(Card("8 of Diamonds", 8))
deck_of_cards.append(Card("9 of Diamonds", 9))
deck_of_cards.append(Card("10 of Diamonds", 10))
deck_of_cards.append(Card("Jack of Diamonds", 11))
deck_of_cards.append(Card("Queen of Diamonds", 12))
deck_of_cards.append(Card("King of Diamonds", 13))
deck_of_cards.append(Card("Ace of Diamonds", 14))